services:
  nyuroprint:
    build:
      context: ./nyuroprint
      dockerfile: Dockerfile
    runtime: nvidia  # Включаем поддержку NVIDIA
    ports:
      - "3000:3000"
    networks:
      - my_network
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [ gpu ]
    # Параметры для лучшей производительности
    ipc: host
    ulimits:
      memlock:
        soft: -1
        hard: -1
      stack:
        soft: 67108864
        hard: 67108864
    volumes:
      - ./nyuroprint:/ai
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./.:/home/app/
      - ./uploads:/uploads
      - ./ssl:/ssl
    depends_on:
      - db
    networks:
      - my_network
  db:
    image: postgres:16
    env_file: .env
    expose:
      - 5432
    networks:
      - my_network

networks:
  my_network:
