services:
  nyuroprint:
    build:
      context: ./nyuroprint
      dockerfile: Dockerfile
    runtime: nvidia  # Включаем поддержку NVIDIA
    ports:
      - "3000:3000"
    networks:
      - my_network
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [ gpu ]
    # Параметры для лучшей производительности
    ipc: host
    ulimits:
      memlock:
        soft: -1
        hard: -1
      stack:
        soft: 67108864
        hard: 67108864
    volumes:
      - ./nyuroprint:/ai
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./.:/home/app/
      - ./uploads:/uploads
      - ./ssl:/ssl
    depends_on:
      - db
    networks:
      - my_network
  db:
    image: postgres:16
    env_file: .env
    expose:
      - 5432
    networks:
      - my_network

  tg_support:  # Поменяли имя сервиса на tg_support
      build:
        context: ./tg_support_site  # Папка с вашим приложением
        dockerfile: Dockerfile        # Dockerfile для tg_support_site
      ports:
        - "8765:8765"  # Порт для вашего приложения FastAPI
      volumes:
        - ./tg_support_site:/home/app
        - ./.env:/app/.env  # Подключаем .env файл
        - ./ssl:/ssl
      networks:
        - my_network
      depends_on:
        - db
      environment:
        - PYTHONUNBUFFERED=1

networks:
  my_network:
