version: "3"
services:
  nyuroprint:
    build:
      context: ./nyuroprint
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - my_network
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./app/:/home/app/
      - ./uploads:/uploads
      - ./ssl:/ssl
    depends_on:
      - db
    networks:
      - my_network
  db:
    image: postgres:16
    env_file: .env
    expose:
      - 5432
    networks:
      - my_network

networks:
  my_network:
